### ISSUE TITLE
Release to maven central?

### ISSUE THREAD

**Issue by jhovell** [researchgate/archaius-consul#1]
Hi there @Hillkorn,

Any plans to cut a release version and publish this in Maven central? Would just be a timesaver for folks so they don't need to set up their own CI environment and keep the fork up to date with your repo.

This is a handy library!

**Comment by jhovell** [comment]
Nevermind. I did not notice that the 0.1.2 version was released. For some reason Googling didn't turn it up either. Thanks!

**Comment by Hillkorn** [comment]
Your'e welcome :)
I'll also try to release it to maven central in near future.
