### ISSUE TITLE
issue with calculating length of the key

### ISSUE THREAD

**Issue by im2kul** [researchgate/archaius-consul#2]
Hi,

   I believe there may be some issue with calculating the length of the key. When I set my key as "/user-service.lab.config" I get an exception at Line 59 in ConsulConfigurationSource.java 

properties.put(value.getKey().substring(length), new String(decoded));

  The reason is that by the time the key come to this code path,"/" as the beginning of the key has been striped off but the length still reflects to have the "/" there (24).

`Exception in thread "main" java.lang.RuntimeException: Unable to load Properties source from net.researchgate.archaius.ConsulConfigurationSource@4a883b15
    at com.netflix.config.AbstractPollingScheduler.initialLoad(AbstractPollingScheduler.java:82)
    at com.netflix.config.AbstractPollingScheduler.startPolling(AbstractPollingScheduler.java:200)
    at com.netflix.config.DynamicConfiguration.startPolling(DynamicConfiguration.java:60)
    at com.netflix.config.DynamicConfiguration.<init>(DynamicConfiguration.java:42)
    at com.fanatics.consul.client.app.ConsulClient.init(ConsulClient.java:31)
    at com.fanatics.consul.client.app.ConsulClient.<init>(ConsulClient.java:19)
    at com.fanatics.consul.client.app.ConsulClient.main(ConsulClient.java:57)
Caused by: java.lang.NullPointerException
    at com.netflix.config.AbstractPollingScheduler.initialLoad(AbstractPollingScheduler.java:79)
    ... 6 more`

**Comment by Hillkorn** [comment]
Hey, i'll checking that issue and it seems to be a different reason. I thought i can return null if nothing shall change but unfortunately it does a call on that null and this error occurs. I think your client never connected successfully, could you please check that you can connect

new ConsulClient(host, port)

and try to get something from consul.

Thanks

**Comment by Hillkorn** [comment]
Yes, seems there is some problem with it. Im on it.

**Comment by Hillkorn** [comment]
Released 0.1.3, could you please checkout if it works now.

Thanks

**Comment by im2kul** [comment]
Thanks Dennis. I will let you know once I try it out

Thanks

**Comment by im2kul** [comment]
This does not seem to have resolved the issue.

`SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[Ljava.lang.StackTraceElement;@2e6a8155
Exception in thread "main" java.lang.RuntimeException: Unable to load Properties source from net.researchgate.archaius.ConsulConfigurationSource@25641d39
    at com.netflix.config.AbstractPollingScheduler.initialLoad(AbstractPollingScheduler.java:82)
    at com.netflix.config.AbstractPollingScheduler.startPolling(AbstractPollingScheduler.java:200)
    at com.netflix.config.DynamicConfiguration.startPolling(DynamicConfiguration.java:60)
    at com.netflix.config.DynamicConfiguration.<init>(DynamicConfiguration.java:42)
    at com.fanatics.consul.client.app.ConsulClient.init(ConsulClient.java:33)
    at com.fanatics.consul.client.app.ConsulClient.<init>(ConsulClient.java:20)
    at com.fanatics.consul.client.app.ConsulClient.main(ConsulClient.java:62)
Caused by: java.lang.NullPointerException
    at com.netflix.config.AbstractPollingScheduler.initialLoad(AbstractPollingScheduler.java:79)
    ... 6 more`

Run through this simple code:
`String hosts = "<SOME_IP_1>:8500,<SOME_IP_2>:8500,<SOME_IP_3>:8500";
        String rootPath = "/user-service.lab.config";
        ConsulConfigurationSource consulConfigurationSource = new ConsulConfigurationSource(hosts, rootPath);
        DynamicConfiguration dynamicConfiguration = new DynamicConfiguration(consulConfigurationSource, new FixedDelayPollingScheduler(-1, 30000, false));
        ConfigurationManager.install(dynamicConfiguration);
`
You will find that the exception still happens in ConculConfigurationSource Line 62

Please note that my key was "/user-service.lab.config" which has a length of 24. However, when the code path comes to Line 62 in ConsulConfigurationSource, the key now is "user-service.lab.config" and the length is still 24 which is wrong. Length should have been 23 or the "/" should never have been wiped out.

**Comment by im2kul** [comment]
Also: properties.put(value.getKey().substring(length), new String(decoded)); (line 62 in ConsulConfigurationSource), there is some issue with that line of code?

When you do a substring of the length of the key, you are inserting an empty string as part of properties.put. Don't you need properties.put(value.getKey().substring(0,length), new String(decoded))?

**Comment by Hillkorn** [comment]
Sorry i should rename that var length. It is the starting point of key the string. If you would do it like your example it would contain the whole path without last part behind the /.

**Comment by im2kul** [comment]
Even if I place my without any "/", this would still fail as you add one to the length this this line:
            this.length = facility.length() + (facility.charAt(0) == '/' ? 0 : 1) - (facility.endsWith("/") ? 1 : 0);

Specifically: (facility.charAt(0) == '/' ? 0 : 1)

**Comment by Hillkorn** [comment]
Could you try a config source with a roothPath = "/" or "/user-service.lab.config/"

**Comment by Hillkorn** [comment]
Finally i think i can reproduce it and will fix it

**Comment by Hillkorn** [comment]
Hmm can't reproduce it really with a test and the (facility.charAt(0) == '/' ? 0 : 1) is because the key that consul returns is without a leading / so i have to ignore that if it is given.

**Comment by im2kul** [comment]
Then something wrong with the computation: It should have returned 23 as length and not 24. That's the reason you get Index Out Of Bounds -1 exception

this.length = facility.length() + (facility.charAt(0) == '/' ? 0 : 1) - (facility.endsWith("/") ? 1 : 0);

This same length is used for storing the the KV in the properties on Line 62
properties.put(value.getKey().substring(**length**), new String(decoded));

Run This code:
        String facility = "user-service.lab.config";
        int length = facility.length() + (facility.charAt(0) == '/' ? 0 : 1) - (facility.endsWith("/") ? 1 : 0);  
        System.out.println("Length of the key: "+length);
You will find that it will print 24 and NOT 23.which is wrong. 

Maybe this part of the code 
((facility.charAt(0) == '/' ? 0 : 1)) 
should be:
(facility.charAt(0) == '/' ? 1 : 0)

**Comment by Hillkorn** [comment]
If you set user-service.lab.config which is 23 length the returned entries will look like
key=> user-service.lab.config/something
key=> user-service.lab.config/different.entry
and now you have user-service.lab.config/ as root path and this is 24 length.
If you now call substring on it with 24 it will return the rest path like
key=>something
key=>different.entry

All paths that end with / should be ignored

**Comment by Hillkorn** [comment]
As i see i implemented a bug with 0.13.0 that will occur if you have a path ot "/"

**Comment by Hillkorn** [comment]
And i forgot to say that if you store or set something for /user-service.lab.config/something the returned key will be user-service.lab.config/something

**Comment by im2kul** [comment]
Well...maybe I am not understanding how you expect me to store KV

If I do a query to my Consul cluster:
http://<SOME_IP>:8500/v1/kv/?recurse

My response looks like the following

`
[
    {
        "LockIndex": 0,
        "Key": "user-service.lab.config",
        "Flags": 0,
        "Value": "dGVzdDE9YW5zamRqZmsgaGVoZWhlaGU=",
        "CreateIndex": 108263,
        "ModifyIndex": 108263
    },
    {
        "LockIndex": 0,
        "Key": "vault/auth/fdc2d905-4d0f-7034-df9f-3299f0a97c87/salt",
        "Flags": 0,
        "Value": "AAAAAQJ4orINh+FxohrlSogtvAxP3qk5beCHUSqanM4bvhMUA+ZFRrE4mYHmAmCWGK3yMFIn0vewsL2JtzjCjLHTluWF",
        "CreateIndex": 89,
        "ModifyIndex": 89
    },
.......
`
What do you expect my key to be for the root path? "/user-service.lab.config" or "/"?

I only want to make sure that I get a call back when user-service.lab.config is changed

**Comment by Hillkorn** [comment]
I think then you should use "/"
What we do is /name-of-service/ so that all direct entries in "name-of-service" are set as properties so
key=> name-of-service/xyz
value=>test-config
and now with rootPath = name-of-service you get in your config
xyz => test-config
So rootPath should only be a path to a folder or how it was called in consul

**Comment by im2kul** [comment]
with "/" there seems to be an issue with the key that is stored. The the key that is stored is "ser-service.lab.config" instead of "user-service.lab.config"

again this is because of 
 properties.put(value.getKey().substring(length), new String(decoded))

Please try it out. When I try to get back the property "user-service.lab.config" it is null but when I get "ser-service.lab.config" it is correct. 

This is how I get back the property dynamicConfiguration.getProperty(key)

**Comment by Hillkorn** [comment]
But your response tells you exactly that
This "user-service.lab.config" is the key in
[ { "LockIndex": 0, "Key": "user-service.lab.config", "Flags": 0, "Value": "dGVzdDE9YW5zamRqZmsgaGVoZWhlaGU=", "CreateIndex": 108263, "ModifyIndex": 108263 }, { "LockIndex": 0, "Key": "vault/auth/fdc2d905-4d0f-7034-df9f-3299f0a97c87/salt", "Flags": 0, "Value": "AAAAAQJ4orINh+FxohrlSogtvAxP3qk5beCHUSqanM4bvhMUA+ZFRrE4mYHmAmCWGK3yMFIn0vewsL2JtzjCjLHTluWF", "CreateIndex": 89, "ModifyIndex": 89 }

**Comment by Hillkorn** [comment]
Try 0.1.2 or 0.1.4 please
Cause of a missunderstanding i implemented a bug as a fix :/

**Comment by im2kul** [comment]
thats exactly my point. The response says "Key": "user-service.lab.config" but when I query using your client with "user-service.lab.config" it returns back NULL. However when I query "ser-service.lab.config" it is fine

What do you expect  value.getKey() to return? 

In the case where I have "/", my length is 1 (based on your current code changes). That means value.getKey().substring(length) would return "ser-service.lab.config" NOT "**u**ser-service.lab.config"

**Comment by Hillkorn** [comment]
Sorry have missread your comment before.
Tried you the different version?

**Comment by im2kul** [comment]
Ok thanks. I will try it out.

**Comment by Hillkorn** [comment]
Did it work?

**Comment by Hillkorn** [comment]
if you still have problems then we can reopen it.

**Comment by im2kul** [comment]
Hi Dennis,

```
Thanks for following up. Yes this seems to be working fine.
```

Thanks
